---
title: Incognitech
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: "/:title/"
exclude:
- ".rvmrc"
- ".rbenv-version"
- README.md
- Rakefile
- changelog.md
highlighter: rouge
tagline: Ramblings of an Incognito Mind :P
author:
  name: Udit Desai
  email: desaiuditd@gmail.com
  github: desaiuditd
  twitter: desaiuditd
  position: Web Developer
  pic: udit
github_repo: https://github.com/desaiuditd/desaiuditd.github.io
production_url: http://blog.incognitech.in
JB:
  version: 0.3.0
  BASE_PATH: false
  ASSET_PATH: "/assets/themes/agency"
  archive_path: "/blog/"
  categories_path: "/categories/"
  portfolio_path: "/portfolio/"
  tags_path: "/tags/"
  atom_path: "/atom.xml"
  rss_path: "/rss.xml"
  comments:
    provider: disqus
    disqus:
      short_name: blogincognitechin
    livefyre:
      site_id: 
    intensedebate:
      account: 
    facebook:
      appid: 
      num_posts: 
      width: 
      colorscheme: 
  analytics:
    provider: google
    google:
      tracking_id: UA-46748923-1
    getclicky:
      site_id: '100776624'
  sharing:
    provider: false
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333
social:
- title: twitter
  url: https://twitter.com/desaiuditd
- title: linkedin
  url: https://linkedin.com/in/desaiuditd
- title: google-plus
  url: https://plus.google.com/+UditDesaiIncog
- title: instagram
  url: http://instagram.com/desaiuditd
- title: github
  url: https://github.com/desaiuditd
markdown: kramdown
plugins:
- jemoji
- jekyll-sitemap
- jekyll-mentions
